- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: present 
      update_cache: true

  - name: Install ca-certificates
    apt:
      name: ca-certificates
      state: present
      update_cache: true

  - name: Install kubectl
    apt:
      name: community.kubernetes.k8s
      state: present
      update_cache: true

